server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern:/templates/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12255899
    initialSize: 20
    minIdle: 50
    maxActive: 500




  application:
    name: sxbs-mall-consumer
  # 多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
  # 设置 为true ,即 允许 同名
  main:
    allow-bean-definition-overriding: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

