spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xhd_guofang?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12255899
    initialSize: 20
    minIdle: 50
    maxActive: 500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
